name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro']

    steps:
    - uses: actions/checkout@v1
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install gem
      run: gem install cocoapods
    - name: Update pod
      run: (cd Example && pod update)
    - name: Install pod
      run: pod install --project-directory=Example
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
    - name: Test
      run: set -o pipefail && xcodebuild clean build-for-testing  -enableCodeCoverage YES -workspace Example/AWAREFramework.xcworkspace -scheme AWAREFramework-Example -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
      env: 
        destination: ${{ matrix.destination }}
    - name: Dry-run
      run: pod lib lint --allow-warnings
      
      
